fyp-marking-system/config/routes.rb
Rails.application.routes.draw do

  resources :students do
    resources :marks
  end

  root 'students#index'

  get 'students/:id/marks/new' => 'marks#new'
  get 'students/:id/marks/:id' => 'marks#show'

end

fyp-marking-system/app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :student
end

fyp-marking-system/app/models/student.rb
class Student < ActiveRecord::Base

has_many :marks

has_attached_file :document
validates_attachment :document, :content_type => { :content_type => %w(application/pdf) }
end

fyp-marking-system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

fyp-marking-system/app/controllers/marks_controller.rb
class MarksController < ApplicationController
	def create
		@student = Student.find(params[:student_id])
		@mark = @student.marks.create(params[:mark].permit(:input1, :input2, :input3, :weight1, :weight2, :weight3, :mark1, :mark2, :mark3, :final_mark))
		@mark.save

		if @mark.save
			redirect_to student_path(@student)
		else
			render 'new'
		end
	end

	def new
    	@mark = Mark.new
  	end

  	def update

		if @mark.update
			redirect_to student_path(@student)
		else
			render 'edit'
		end
	end

	def edit
		@mark = Mark.find(params[:id])
	end

	def show
		@student = Student.find(params[:student_id])
	end
	def index
		@student = Student.find(params[:student_id])
	end
	private 
	def set_mark
	    @mark = Mark.find(params[:id])
	end

end

fyp-marking-system/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:StudentNumber, :ProjectTitle, :document, :Reader1, :Reader2, :Reader3)
    end
end

fyp-marking-system/app/helpers/application_helper.rb
module ApplicationHelper
end

fyp-marking-system/app/helpers/marks_helper.rb
module MarksHelper
end

fyp-marking-system/app/helpers/students_helper.rb
module StudentsHelper
end

fyp-marking-system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FypMarkingSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="nav">
        <%= link_to "Home", root_path%>
    </div>    


<%= yield %>
<footer class="footer">
      <div class="container">
        <p class="text-muted">FYP Marking System ©2016</p>        
      </div>
</footer>
</body>
</html>

fyp-marking-system/app/views/marks/_form.html.erb
<%= form_for [:student, @mark], html: {multipart: true} do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this grading from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Introduction' %>
    <div class="form" class="col-xs-5">
      <%= f.text_area :input1, placeholder:"Comment", class:"form-control", size:"10x5"%>
      <br>
      <%= f.number_field :weight1, placeholder:"Weight",id:"weight1" %>
      <%= f.number_field :mark1, placeholder:"Mark",id:"mark1"%>
    </div>
  </div>

  <div class="field">
    <%= f.label 'Main' %>
    <div class="form">
      <%= f.text_area :input2 , placeholder:"Comment", class:"form-control", size:"10x5"%>
      <br>
      <%= f.number_field :weight2, placeholder:"Weight",id:"weight2" %>
      <%= f.number_field :mark2, placeholder:"Mark",id:"mark2" %>
    </div>
  </div>

  <div class="field">
    <%= f.label 'Conclusion' %>
    <div class="form">
      <%= f.text_area :input3 , placeholder:"Comment", class:"form-control", size:"10x5"%>
      <br>
      <%= f.number_field :weight3 , placeholder:"Weight",id:"weight3"%>
      <%= f.number_field :mark3, placeholder:"Mark",id:"mark3"%>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class:"btn-xs btn-success"%>
  </div>
 
  <p id="out"></p>
  <%= f.hidden_field :final_mark , id:"final_mark"%>
<% end %>

<script>
  
  $("#mark1,#mark2,#mark3, #weight1,#weight2,#weight3")
  .keyup(function() {
    var mark1 = Number($( "#mark1").val());
    var mark2 = Number($( "#mark2").val());
    var mark3 = Number($( "#mark3").val());
    var weight1 = Number($( "#weight1").val())/100;
    var weight2 = Number($( "#weight2").val())/100;
    var weight3 = Number($( "#weight3").val())/100;
    var res = (mark1*weight1 + mark2*weight2 + mark3*weight3);
    var finalRes = parseFloat(Math.round(res* 100) / 100).toFixed(2);
    $("#out").text(finalRes +"%");
    document.getElementById("final_mark").value = finalRes;
    
  })
 
  .keyup();
</script>

fyp-marking-system/app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

  <% if @student.marks.first %>
  <p>
  <br>
  <h2>First mark</h2>
  <h3>Introduction</h3><br>
  <p>Comment: <%= @student.marks.first.input1 %></p>
  <p>Weight: <%= @student.marks.first.weight1 %></p>
  <p>Mark: <%= @student.marks.first.mark1%></p>
  <h3>Main</h3><br>
  <p>Comment: <%= @student.marks.first.input2 %></p>
  <p>Weight: <%= @student.marks.first.weight2 %></p>
  <p>Mark: <%= @student.marks.first.mark2%></p>
  <h3>Conclusion</h3><br>
  <p>Comment: <%= @student.marks.first.input3 %></p>
  <p>Weight: <%= @student.marks.first.weight3 %></p>
  <p>Mark: <%= @student.marks.first.mark3%></p>
  <br>
   <p> Final Mark:<%= @student.marks.first.final_mark%></p>
</p>
<%else%>
<p>No marks yet</p>
<%end%>


<% if @student.marks.second %>
  <p>
  <br>
  <h2>Second mark</h2>
  <h3>Introduction</h3><br>
  <p>Comment: <%= @student.marks.second.input1 %></p>
  <p>Weight: <%= @student.marks.second.weight1 %></p>
  <p>Mark: <%= @student.marks.second.mark1%></p>
  <h3>Main</h3><br>
  <p>Comment: <%= @student.marks.second.input2 %></p>
  <p>Weight: <%= @student.marks.second.weight2 %></p>
  <p>Mark: <%= @student.marks.second.mark2%></p>
  <h3>Conclusion</h3><br>
  <p>Comment: <%= @student.marks.second.input3 %></p>
  <p>Weight: <%= @student.marks.second.weight3 %></p>
  <p>Mark: <%= @student.marks.second.mark3%></p>
  <br>
   <p> Final Mark:<%= @student.marks.second.final_mark%></p>
</p>
<%else%>
<p>No second mark yet</p>
<%end%>

<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>

fyp-marking-system/app/views/marks/new.html.erb
<h1>New Grade</h1>
<%= render 'form' %>
<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>

fyp-marking-system/app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

  <h1>Marks</h1>
  <% if @student.marks.first %>
  <p>
  <br>
  <h2>First mark</h2>
  <h3>Introduction</h3><br>
  <p>Comment: <%= @student.marks.first.input1 %></p>
  <p>Weight: <%= @student.marks.first.weight1 %></p>
  <p>Mark: <%= @student.marks.first.mark1%></p>
  <h3>Main</h3><br>
  <p>Comment: <%= @student.marks.first.input2 %></p>
  <p>Weight: <%= @student.marks.first.weight2 %></p>
  <p>Mark: <%= @student.marks.first.mark2%></p>
  <h3>Conclusion</h3><br>
  <p>Comment: <%= @student.marks.first.input3 %></p>
  <p>Weight: <%= @student.marks.first.weight3 %></p>
  <p>Mark: <%= @student.marks.first.mark3%></p>
  <br>
   <p> Final Mark:<%= @student.marks.first.final_mark%></p>
</p>
<%else%>
<p>No marks yet</p>
<%end%>


<% if @student.marks.second %>
  <p>
  <br>
  <h2>Second mark</h2>
  <h3>Introduction</h3><br>
  <p>Comment: <%= @student.marks.second.input1 %></p>
  <p>Weight: <%= @student.marks.second.weight1 %></p>
  <p>Mark: <%= @student.marks.second.mark1%></p>
  <h3>Main</h3><br>
  <p>Comment: <%= @student.marks.second.input2 %></p>
  <p>Weight: <%= @student.marks.second.weight2 %></p>
  <p>Mark: <%= @student.marks.second.mark2%></p>
  <h3>Conclusion</h3><br>
  <p>Comment: <%= @student.marks.second.input3 %></p>
  <p>Weight: <%= @student.marks.second.weight3 %></p>
  <p>Mark: <%= @student.marks.second.mark3%></p>
  <br>
   <p> Final Mark:<%= @student.marks.second.final_mark%></p>
</p>
<%else%>
<p>No second mark yet</p>
<%end%>

<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>

fyp-marking-system/app/views/students/_form.html.erb
<%= form_for @student, html: {multipart: true} do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Student Number' %><br>
    <%= f.number_field :StudentNumber, max:99999999 %>
  </div>
  <div class="field">
    <%= f.label 'Project Title' %><br>
    <%= f.text_area :ProjectTitle %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.file_field :document %>
  </div>
  <div class="field">
    <%= f.label 'Reader 1' %><br>
    <%= f.text_area :Reader1 %>
  </div>
  <div class="field">
    <%= f.label 'Reader 2' %><br>
    <%= f.text_area :Reader2 %>
  </div>
  <div class="field">
    <%= f.label 'Reader 3' %><br>
    <%= f.text_area :Reader3 %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn-xs btn-success"%>
  </div>

<% end %>

fyp-marking-system/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>
<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>

fyp-marking-system/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>Students</h1>
</div>

<div class="container">
      <h3> <%= link_to 'Add Student', new_student_path,  style: "color:white", class:"btn btn-warning center-block"%> </h3>

      <br>
  <table>
    <thead>
      <tr>
        <th>Student Number</th>
        <th>Project Title</th>
        <th>Project PDF</th>      
        <th>Reader 1</th>
        <th>Reader 2</th>
        <th>Reader 3</th>
        <th>Mark 1</th>
        <th>Mark 2</th>
        <th>Mark 3</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.StudentNumber %></td>
          <td><%= student.ProjectTitle %></td>
          <% if student.document.exists? %>
            <td><%= link_to 'PDF', student.document.url(:original, false), style: "color:white", class:"btn-xs btn-primary" %></td>
          <% else %>
            <td><%= 'No PDF uploaded' %></td>
          <% end %>
          
          <% if student.Reader1.empty?%>
              <td><%= student.Reader3 %></td>
          <% else %>

            <% if student.Reader1.empty?%>
                <td><%= student.Reader3 %></td>
            <% else %>
                <td><%= button_tag student.Reader1, class:"btn-xs btn-primary" %></td>
            <% end %>
          <% end %>
          <% if student.Reader2.empty?%>
              <td><%= student.Reader3 %></td>
          <% else %>
          <td><%= button_tag student.Reader2, class:"btn-xs btn-primary" %></td>
          <% end %>
          <% if student.Reader3.empty?%>
              <td><%= student.Reader3 %></td>
          <% else %>
            <td><%= button_tag student.Reader3, class:"btn-xs btn-primary" %></td>
          <% end %>
          <% if student.marks %>
          <% if student.marks.first %>
          <td><%= student.marks.first.final_mark %></td>
          <%else%>
          <td>None</td>
          <% end %>

          <% if student.marks.second%>
          <td><%= student.marks.second.final_mark %></td>
          <%else%>
          <td>None</td>
          <% end %>

          <% if student.marks.third%>
          <td><%= student.marks.third.final_mark %></td>
          <%else%>
          <%if student.marks.first && student.marks.second  %>

          <%if (student.marks.first.final_mark - student.marks.second.final_mark).abs >= 10 && student.Reader3.empty? %>
          <td><%= button_tag "Third marker needed", class:"btn-xs btn-danger" %></td>
          <%else %>
          <%if (student.marks.first.final_mark - student.marks.second.final_mark).abs >= 10 && !student.Reader3.empty? %>
          <td><%= button_tag "Third mark needed", class:"btn-xs btn-warning" %></td>
          <%else%>
          <td><%= button_tag "No third marker needed", class:"btn-xs btn-success" %></td>
          <%end%>
          <%end%>
          <%else %>
          <td>None</td>
          <% end %>
          <% end %>
          <%end %>
          <td><%= link_to 'Edit', edit_student_path(student), style: "color:white", class:"btn-xs btn-success" %></td>
          <td><%= link_to 'Mark', student_path(student),  style: "color:white", class:"btn-xs btn-success" %></td>
          <td><%= link_to 'Delete', student,  style: "color:white", class:"btn-xs btn-success", method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

fyp-marking-system/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>

fyp-marking-system/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student Number</strong>
  <%= @student.StudentNumber %>
</p>

<p>
  <strong>Project Title</strong>
  <%= @student.ProjectTitle %>
</p>

<p>
  <strong>Project PDF</strong>
  <% if @student.document.exists? %>
  <%= link_to 'PDF', @student.document.url(:original, false) %>
  <%else%>
  <%='No PDF Uploaded'%>
  <%end%>
</p>


<% if @student.marks.first && @student.marks.second && @student.marks.third %>
<%= link_to 'View Marks', student_marks_path(@student), style: "color:white" , class:"btn-sm btn-warning"%> 
<%end%>

<% if !@student.marks.first || !@student.marks.second %>
<p>
  <strong>Reader 1</strong>
  <%= @student.Reader1 %>
  <p> <%= link_to 'Add Mark', new_student_mark_path(@student), style: "color:white" , class:"btn-sm btn-warning"%> </p>
</p>

<p>
  <strong>Reader 2</strong>
  <%= @student.Reader2 %>
  <p> <%= link_to 'Add Mark', new_student_mark_path(@student), style: "color:white" , class:"btn-sm btn-warning"%> </p>
</p>
<%end%>

<% if @student.marks.first && @student.marks.second && !@student.marks.third && @student.Reader3.empty?%>
<%= link_to 'View Marks', student_marks_path(@student), style: "color:white" , class:"btn-sm btn-warning"%> 
<%end%>


<% if @student.marks.first && @student.marks.second && !@student.marks.third && !@student.Reader3.empty?%>
<%= link_to 'View Marks', student_marks_path(@student), style: "color:white" , class:"btn-sm btn-warning"%> 
 <strong>Reader 3</strong>
  <%= @student.Reader3 %>
  <br>
  <p><%= link_to 'Add Third Mark', new_student_mark_path(@student), style: "color:white" , class:"btn-sm btn-warning"%></p>
<%end%>

<br><br>
<%= link_to 'Edit', edit_student_path(@student), style: "color:white", class:"btn-xs btn-success" %> |
<%= link_to 'Back', students_path, style: "color:white", class:"btn-xs btn-success" %>